/**
 * Auto-generated skill index
 * Total skills: 39
 */

module.exports = {
  'agent-introspection-debugging': require('./agent-introspection-debugging'),
  'agent-sort': require('./agent-sort'),
  'api-design': require('./api-design'),
  'article-writing': require('./article-writing'),
  'backend-patterns': require('./backend-patterns'),
  'benchmark-methodology': require('./benchmark-methodology'),
  'brand-discovery': require('./brand-discovery'),
  'brand-voice': require('./brand-voice'),
  'bun-runtime': require('./bun-runtime'),
  'coding-standards': require('./coding-standards'),
  'competitive-platform-analysis': require('./competitive-platform-analysis'),
  'competitive-report-structure': require('./competitive-report-structure'),
  'content-engine': require('./content-engine'),
  'crosspost': require('./crosspost'),
  'deep-research': require('./deep-research'),
  'dmux-workflows': require('./dmux-workflows'),
  'documentation-lookup': require('./documentation-lookup'),
  'e2e-testing': require('./e2e-testing'),
  'eval-harness': require('./eval-harness'),
  'everything-claude-code': require('./everything-claude-code'),
  'exa-search': require('./exa-search'),
  'fal-ai-media': require('./fal-ai-media'),
  'frontend-patterns': require('./frontend-patterns'),
  'frontend-slides': require('./frontend-slides'),
  'investor-materials': require('./investor-materials'),
  'investor-outreach': require('./investor-outreach'),
  'market-research': require('./market-research'),
  'mcp-server-patterns': require('./mcp-server-patterns'),
  'mle-workflow': require('./mle-workflow'),
  'nextjs-turbopack': require('./nextjs-turbopack'),
  'plan-canvas': require('./plan-canvas'),
  'product-capability': require('./product-capability'),
  'security-review': require('./security-review'),
  'strategic-compact': require('./strategic-compact'),
  'tdd-workflow': require('./tdd-workflow'),
  'unified-memory': require('./unified-memory'),
  'verification-loop': require('./verification-loop'),
  'video-editing': require('./video-editing'),
  'x-api': require('./x-api'),
};
